# Generated by Django 5.1.7 on 2025-03-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
