# Generated by Django 5.1.7 on 2025-04-01 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_menubooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_menu_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_amount_to_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='user_management.booking')),
            ],
        ),
    ]
