# Generated by Django 5.1.7 on 2025-04-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='billing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
