# Generated by Django 5.1.7 on 2025-04-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_rename_generated_at_billing_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary'), ('prefer-not-to-say', 'Prefer-not-to-say')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
