# Generated by Django 5.1.7 on 2025-04-10 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_diningoffer'),
        ('user_management', '0007_alter_customerprofile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.PositiveIntegerField()),
                ('advance_payment_per_guest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_advance_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.offer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to='restaurant.restaurant')),
                ('seat_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to='restaurant.seatslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to='user_management.customerprofile')),
            ],
        ),
    ]
