# Generated by Django 5.1.7 on 2025-04-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_diningoffer'),
        ('user_management', '0009_remove_seatbooking_advance_payment_per_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='menubooking',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_bookings', to='restaurant.table'),
            preserve_default=False,
        ),
    ]
