# Generated by Django 5.1.7 on 2025-04-10 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_menubooking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menubooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='user_management.seatbooking'),
        ),
    ]
