# Generated by Django 5.1.7 on 2025-04-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
