# Generated by Django 5.1.7 on 2025-04-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='lock_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='queue_priority',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
