# Generated by Django 5.1.7 on 2025-04-19 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0016_seatbooking_lock_expiry_seatbooking_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRequestForSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_request', to='user_management.seatbooking')),
            ],
        ),
    ]
