# Generated by Django 5.1.7 on 2025-04-23 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_alter_billing_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_request_message', to='user_management.seatbooking')),
            ],
        ),
    ]
