# Generated by Django 5.1.7 on 2025-04-23 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0019_specialrequestmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialrequestmessage',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_request_message', to='user_management.menubooking'),
        ),
    ]
