# Generated by Django 5.1.7 on 2025-04-28 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_alter_restaurantstaffprofile_user'),
        ('user_management', '0022_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='complete_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing',
            name='table',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='menu_billings', to='restaurant.table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='user_management.seatbooking'),
        ),
        migrations.AlterField(
            model_name='menubooking',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='user_management.seatbooking'),
        ),
    ]
