# Generated by Django 5.1.7 on 2025-04-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0023_billing_complete_order_billing_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('special_request', 'Special Request'), ('refund_request', 'Refund Request')], default='special_request', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
