# Generated by Django 5.1.7 on 2025-04-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0024_notification_type_notification_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialrequestmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
