# Generated by Django 5.1.7 on 2025-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0025_specialrequestmessage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='queue_priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
