# Generated by Django 5.1.7 on 2026-06-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0027_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='locked_until',
        ),
    ]
