# Generated by Django 5.1.7 on 2026-06-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0029_billing_payment_status_billing_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
