# Generated by Django 5.1.7 on 2026-06-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0033_restaurant_latitude_restaurant_longitude'),
        ('user_management', '0030_seatbooking_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_billings', to='restaurant.table'),
        ),
    ]
