# Generated by Django 5.1.7 on 2025-03-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menu_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20)),
                ('no_of_seats', models.PositiveIntegerField()),
                ('qr_code', models.ImageField(blank=True, default='static/qrcodes/static_qr_placeholder.png', null=True, upload_to='static/qrcodes/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant')),
            ],
        ),
    ]
