# Generated by Django 5.1.7 on 2025-03-27 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='restaurant.restaurant'),
        ),
    ]
