# Generated by Django 5.1.7 on 2025-04-08 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/restaurants/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='map_link',
            field=models.URLField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.PositiveIntegerField()),
                ('booking_available', models.BooleanField(default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('interval_minutes', models.PositiveIntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='SeatSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_seats', models.PositiveIntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_slots', to='restaurant.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'date', 'start_time')},
            },
        ),
    ]
