# Generated by Django 5.1.7 on 2025-04-08 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_restaurant_image_alter_restaurant_map_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seatslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seatslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
