# Generated by Django 5.1.7 on 2025-04-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_seats_created_at_seats_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='booking_available',
        ),
    ]
