# Generated by Django 5.1.7 on 2025-04-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='average_bill_for_two',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='food_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='average_bill_for_two',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='food_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
