# Generated by Django 5.1.7 on 2025-04-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_remove_menu_average_bill_for_two_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Gallery',
        ),
    ]
