# Generated by Django 5.1.7 on 2025-04-22 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_diningoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='no_of_seats',
        ),
        migrations.CreateModel(
            name='TableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tables', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_config', to='restaurant.restaurant')),
            ],
        ),
    ]
