# Generated by Django 5.1.7 on 2025-04-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
