# Generated by Django 5.1.7 on 2025-04-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_server_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='email',
        ),
    ]
