# Generated by Django 5.0.2 on 2025-06-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0028_alter_menu_minimum_wait_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="minimum_wait_time",
            field=models.TextField(default="In minutes"),
        ),
    ]
