# Generated by Django 5.0.2 on 2025-06-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0029_alter_menu_minimum_wait_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="static/qrcodes/"),
        ),
    ]
