# Generated by Django 5.0.2 on 2025-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0030_alter_table_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
