# Generated by Django 5.0.2 on 2025-06-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0031_alter_table_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="performance",
            name="entry_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
